### PR TITLE
RHBPMS-1591 - Fix missing i18n for perspective title

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge (when green).

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
@cristianonicolai could you please take a look on conflicts?

**Comment by paulovmr** [comment]
@cristianonicolai @ederign I was fixing some bundles in this project, and I am preparing a PR with this and more fixes. Would you mind if we do not merge this PR to make my life easier? :)

**Comment by paulovmr** [comment]
The changes on this PR were included here: https://github.com/uberfire/uberfire-extensions/pull/290/files

**Comment by cristianonicolai** [comment]
@paulovmr no worries, closing this one, thanks.

**Pull request closed without merging**
