### PR TITLE
UF-260: Provider's settings and ADD/DELETE group capabilities for Wildfly/EAP sec. management providers

### PR DESCRIPTION
**Pull request by romartin**
- Refactored API by adding the provider's settings service and the different settings implementation for the different providers. 
- Added ADD and DELETE capabilites support for Wildfly / EAP.

### CODE REVIEW

**Comment by romartin** [comment]
Added the missing .gitignore files too in the commit.

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
master: 8e7cc3ed23187099a5424b1182845ba7f951806e

**Comment by romartin** [comment]
@csadilek thanks!!! :)

**Pull request closed without merging**
