### PR TITLE
BZ-1265604, BZ-1266138: Now PriorityDisposables need register itself …

### PR DESCRIPTION
**Pull request by porcelli**
…due a WAS issue.

### CODE REVIEW

**Comment by manstis** [comment]
Looks ok other than missing licenses :-(

**Comment by porcelli** [comment]
@manstis license will come in a new PR for all codebase.

**Comment by manstis** [comment]
Other than missing licenses; +1 to merge.

**Comment by csadilek** [comment]
Thanks.

master: 2f00ec0efc0313afbeadc6108659d522c793968e

**Pull request closed without merging**
