### PR TITLE
GUVNOR-2464: Move StyleHelper from kie-wb-common to uberfire-extensions

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/GUVNOR-2464

### CODE REVIEW

**Comment by manstis** [comment]
Also see https://github.com/droolsjbpm/kie-wb-common/pull/312

**Comment by manstis** [comment]
@porcelli ...

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
I suspect CI error relates to (what appears to be) a duff Errai SNAPSHOT build..

**Comment by csadilek** [comment]
Jenkins please retest this.

**Comment by csadilek** [comment]
master: 65f9e7a84fe55249017fa4896e49b1e086ec8da7

**Comment by psiroky** [comment]
Just FYI: Errai is now part of the PR builds, so the latest sources are always cloned and build before the UF repos (to avoid the possibility of  duff SNAPSHOTs downloaded from remote repo).

**Pull request closed without merging**
