### PR TITLE
BZ-1245729 - REST API access using a browser invalidates the session

### PR DESCRIPTION
**Pull request by mswiderski**
(cherry picked from commit 57bb17f3b60fdabd2dec9c6d36304c1b6f212193)

back port of #244

### CODE REVIEW

**Comment by csadilek** [comment]
0.8.x: 7fb0064115f7d8b59abc66327d9a84a98222e009

**Comment by csadilek** [comment]
@mswiderski hm this actually doesn't compile on 0.8.x. Shouldn't have merged / thought I ran the build successfully but didn't apparently. I will send a PR with a fix.

**Comment by mswiderski** [comment]
interesting, wound this be java version difference explaining why it worked fine on master?

thanks for fixing!

**Comment by csadilek** [comment]
yes, it was just because 0.8.x is compiled for Java < 8, and the sessionProvider needed to final because the "effectively final" trick in Java 8 can't be used ;).

**Pull request closed without merging**
