### PR TITLE
Bug 1187122 - Configurable Workbench: First letter of tag or director y name must be symbol from latin alphabet

### PR DESCRIPTION
**Pull request by Rikkola**
Fix for https://github.com/uberfire/uberfire-extensions/pull/102

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Thanks!

master: b80a9a9deb632472dc8975732fb2dd2468a3674a

**Comment by tomasdavidorg** [comment]
Thanks.

**Comment by Rikkola** [comment]
Thanks for the test  @tomasdavidorg

**Pull request closed without merging**
