### PR TITLE
UF-185: Panel Height Lost when goTo(placeRequest, panel)

### PR DESCRIPTION
**Pull request by paulovmr**
Depends on: https://github.com/uberfire/uberfire/pull/324

### CODE REVIEW

**Comment by paulovmr** [comment]
This PR also fixes the issue [UF-285](https://issues.jboss.org/browse/UF-285).

**Comment by porcelli** [comment]
looks good, waiting for #324

**Comment by ederign** [comment]
+1 thanks @paulovmr

**Comment by csadilek** [comment]
master: 89271bce19450da50c03d5a13b19e3be83f12df6

**Pull request closed without merging**
