### PR TITLE
RHBRMS-3079: Fix user deletion

### PR DESCRIPTION
**Pull request by martinweiler**

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Review by romartin — APPROVED** [review]
Tested on EAP 7.0.x, it works fine :+1: 
Thanks a lot for the contribution @martinweiler ! And sorry for the confusions on the server versions.

**Comment by ederign** [comment]
@romartin should we merge this?

**Comment by romartin** [comment]
@ederign I guess so, this is a severe issue currently affecting some customer, anyway I think some QE guys should test this again probably, I tested a few days ago but not sure if you need some other approval from QE, anyway that's fine for me to merge. 
Thanks!

**Comment by ederign** [comment]
@etirelli @krisv @porcelli are we ok to merge this?

**Comment by etirelli** [comment]
@ederign jenkins says there is a failing test? also, I don't think I am the right person to answer, as I don't know which product version this 0.9.x branch is built into...

**Comment by krisv** [comment]
0.9.x corresponds with 6.5.x, so product 6.4.x, so looks ok to me.  Test failures probably need a quick check but other than that this looks fine to me.  Not sure this is also an issue (and needs a fix) in more recent versions (specifically 7.5.x and master)?

**Comment by romartin** [comment]
@krisv nope - there is no need to backport this commit into recent versions, AFAIK (at least tested recently) this is working fine. Anyway would be good if QE can ensure this still works for the next 7.0 GA, I understand they'll do the right tests in the next weeks, as part of the candidate release testing,  isn't it?

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
it seems that failed tests are on 6.5.x branch too failing so this is not due the changes here

**Comment by mareknovotny** [comment]
@romartin could you merge it?

**Comment by romartin** [comment]
@mareknovotny I have no write access for this repo :( Cannot merge it.. probably @ederign can do it

**Review by ederign — APPROVED** [review]

**Pull request merged**
