### PR TITLE
Translations pulled from Zanata

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by manstis** [comment]
-1 to merge (see comment on other PR re: French single apostrophes - you need to run mvn replacer:replace too)

**Comment by psiroky** [comment]
So is this now ready for merge?

**Comment by cristianonicolai** [comment]
@psiroky I believe so. I've updated both PRs based @manstis guidance to use mvn replacer:replace.

**Comment by manstis** [comment]
+1 to merge.

**Pull request merged**
