### PR TITLE
[6.4.x] RHBPMS-4134: Uploaded files are not displayed in Plugin Management editors

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge... I think we can forego the need to move to errai-ui for a 1 line change :-)

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
@paulovmr did you run a full build locally?

**Comment by paulovmr** [comment]
@ederign Yes, I did, it was successful.

**Comment by ederign** [comment]
+1 seems like a not related error: 
"17:50:11 [ERROR] Failed to execute goal on project cordova-maven-plugin: Could not resolve dependencies for project org.jboss.errai:cordova-maven-plugin:maven-plugin:3.2.5-SNAPSHOT: Could not find artifact org.objenesis:objenesis:jar:1.0 in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/) -> [Help 1]
17:50:11 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project cordova-maven-plugin: Could not resolve dependencies for project org.jboss.errai:cordova-maven-plugin:maven-plugin:3.2.5-SNAPSHOT: Could not find artifact org.objenesis:objenesis:jar:1.0 in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/)"

**Comment by ederign** [comment]
@paulovmr are you applying those fixes to master? (and also changing from ApplicationScope to @EntryPOint? )

**Comment by paulovmr** [comment]
@ederign Yes, I'll work on the 6.5.x and master PRs now. I also plan to fix the upload servlet for images on the uberfire-wires-webapp.

**Comment by ederign** [comment]
@paulovmr  great thanks!

**Pull request merged**
