### PR TITLE
BZ-1274685 - New Repository dialog validation broken when Managed Repository is checked

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit 7a29bcdcf44cf6da27648ef8531a2316cc8ef3a1)

### CODE REVIEW

**Comment by wmedvede** [comment]
Peer PR for https://github.com/uberfire/uberfire-extensions/pull/103

**Comment by wmedvede** [comment]
@manstis 
Hello Mike, would you mind to review this PR?

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
Thanks!

master: c03701768b3569203ea31eeb0982e06cb844237f

**Pull request closed without merging**
