### PR TITLE
[RFC] initial preferences API use

### PR DESCRIPTION
**Pull request by qmx**

### CODE REVIEW

**Comment by qmx** [comment]
this depends on https://github.com/uberfire/uberfire/pull/184

**Comment by manstis** [comment]
I know this is an RFC but I'd like to have seen removal of the "other" Preferences Services entirely, e.g. remove ```UserPreferencesService``` and use your new ```PreferenceStorage``` directly. While other "preferences services" exist I think there's a greater risk of people adding/amending to them in ways that circumvent your new service. Only my opinion :)

**Comment by ederign** [comment]
+1 por @manstis

**Comment by csadilek** [comment]
Closing since uberfire/uberfire#184 was closed.

**Pull request closed without merging**
