### PR TITLE
UF-265: +Improved installation instructions.

### PR DESCRIPTION
**Pull request by romartin**

### CODE REVIEW

**Comment by romartin** [comment]
Only readme's updated :) Thx

**Comment by csadilek** [comment]
@romartin as discussed, please add some clarifications about roles vs groups and what the role managers does. thanks.

**Comment by romartin** [comment]
Yeah @csadilek , please check the update. I try not to give so many detailed info.. so probably adding these lines gives a good global idea now?

**Comment by csadilek** [comment]
@romartin If you don't mind I will rephrase this a bit myself, squash and push it on Monday.

**Comment by romartin** [comment]
@csadilek  sure!! If you need whatever just let me know :)

**Comment by csadilek** [comment]
master: 6081c5df4c8c7ab0debf640f24232116e50b58ec

**Comment by romartin** [comment]
@csadilek  thx for the fixes!!  :)

**Pull request closed without merging**
