### PR TITLE
Avoid running concurrent batch indexing threads for the same FS

### PR DESCRIPTION
**Pull request by csadilek**
This fixes the intermittent test failures of BatchIndexConcurrencyTest [1]
and improves the fix for BZ-1288132 [2]

[1] https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/uberfire-extensions/186/org.uberfire$uberfire-metadata-commons-io/testReport/org.uberfire.ext.metadata.io/BatchIndexConcurrenyTest/testForSingleBatchIndexExecution/
[2] https://github.com/uberfire/uberfire-extensions/commit/7d6764e69

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
@manstis just waiting to see if jenkins is actually happy with this. would've asked for your review after. I hope I am not missing anything but I take your plus one as a good sign ;).

**Comment by manstis** [comment]
I guess the only concern would be runAsync() should be synchronized...

**Comment by csadilek** [comment]
@manstis yes, I had used a concurrenthashmap first before switching to identity....I will update to use a thread-safe set.

**Comment by manstis** [comment]
IMO it's not the indexPending.add(..) that'll need to be thread safe but the invocation of SimpleExecutor... so still suspect it should be the method that is synchronized. Happy to be told otherwise though!

**Comment by csadilek** [comment]
@manstis I would disagree with that because we're first checking the set and only then invoking the executor.

**Comment by manstis** [comment]
To be honest, I'm no concurrency guru, so can accept your comment. Personally I still see potential for concurrency issues between the read and write... but if you're confident CopyOnWriteArraySet fits... then +1 to merge.

**Comment by manstis** [comment]
If there was an atomic getAndSet then I'd agree whole heartedly :-)

**Comment by csadilek** [comment]
@manstis I don't know what you mean. I think you might be misinterpreting what I am trying to do here. It's probably best to chat about it.

**Comment by csadilek** [comment]
Closing this unmerged. The more I think about it the less I like fixing this on that level.

**Pull request closed without merging**
