### PR TITLE
Uberfire table extract css fix

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Comment by ederign** [comment]
@Rikkola this is the css missing for simple tables. I've tested in jbpm-console-ng-showcase.

**Comment by Rikkola** [comment]
@ederign Thank you

**Comment by Rikkola** [comment]
Works also in drools-wb, +1 from me.

**Comment by csadilek** [comment]
master: 4bfd7372ada62c7360cab57497726ad244dbe0eb

**Pull request closed without merging**
