### PR TITLE
BZ1269333: Result of searching Assets in Business Central's 'Full Text Search' includes duplicate records

### PR DESCRIPTION
**Pull request by manstis**
See https://bugzilla.redhat.com/show_bug.cgi?id=1269333

The issue is "additional indexers" also create index entries for "full text" (but with a different ID to the "default indexing"). Consequentially when performing a "full text" search two records were matched: one created by "default indexing" and the other by the "additional indexers".

Fixed and added new test. Existing tests were refactored to use a new common base class to avoid duplication of the setup/dispose etc code.

### CODE REVIEW

**Comment by manstis** [comment]
Related PR: https://github.com/droolsjbpm/kie-wb-common/pull/134

**Comment by manstis** [comment]
@porcelli since you commented on the BZ care to review this?

**Comment by porcelli** [comment]
+1

**Comment by csadilek** [comment]
Thanks!

master: 90c4901f4082fb607b285d1491bd61ee28c6dc48

**Pull request closed without merging**
