### PR TITLE
RHBPMS-4220: Added RoleRegistry and registered principals that come from Keycloak remote logins as roles.

### PR DESCRIPTION
**Pull request by romartin**
Depends on https://github.com/uberfire/uberfire/pull/509

### CODE REVIEW

**Comment by romartin** [comment]
Hi @dgutierr , added tests here as well! Thanks!

**Comment by dgutierr** [comment]
+1 Well done!

**Comment by manstis** [comment]
@romartin @dgutierr This PR is failing to compile with JDK1.6 (required for 0.9.x). Please see https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/uberfire-extensions-0.9.x/26/console

**Comment by csadilek** [comment]
@manstis @romartin after looking into this, it doesn't look like a JDK version issue at all. It looks like when jenkins build uf-ext 0.9.x it didn't pick up the right snapshots/sources from uf 0.9.x. I can't reproduce the problem locally.

**Comment by csadilek** [comment]
@manstis @romartin in fact, uf-ext is green on jenkins too now: https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/uberfire-extensions-0.9.x/

**Comment by romartin** [comment]
@dgutierr @manstis @csadilek yes guys, I ran the build locally using the full profile ( which checks jdk6 verifications ) and just tried againnow, it builds fine as well. Thanks and sorry if any inconveniences!!

**Pull request merged**
