### PR TITLE
UF-284: Changes in CopyPopup and RenamePopup introduces a regresion in WB editors that has FileNameValidators configured for the different assets types

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by manstis** [comment]
@wmedvede Could you please take a look?

**Comment by manstis** [comment]
@paulovmr Thanks for closing the gap so quickly!

**Comment by paulovmr** [comment]
@manstis No problem :)

**Comment by csadilek** [comment]
master: d8ebb6aabfae20a208005c8f9404ae8a8964c8d9

**Pull request closed without merging**
