### PR TITLE
GUVNOR-2342: added tests

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by manstis** [comment]
Hello, license needs updating and IMO the test would be better if it verified after each view.set call - otherwise we're not verifying which call set the footer to which value.

**Comment by jomarko** [comment]
@manstis you are right, I will fix it today.

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
master: d64d8f6e51da915cc359685bc360ba6901646dfa

**Pull request closed without merging**
