### PR TITLE
BZ1007859 - Add 'select all' checkbox to Process instances. Allow che…

### PR DESCRIPTION
**Pull request by nmirasch**
…ckBox header and not to show it at the column picker popup.

### CODE REVIEW

**Comment by csadilek** [comment]
@cristianonicolai can you reviews this, please?

**Comment by cristianonicolai** [comment]
@csadilek this PR looks good but waiting for the work on https://github.com/droolsjbpm/jbpm-console-ng/pull/418 to be finalized before we can merge it.

**Comment by csadilek** [comment]
@cristianonicolai ok uf-ext is gonna be merged into uf tomorrow. So, this PR will have to be recreated. Luckily it's a small one. So, hopefully won't be that bad.

**Comment by nmirasch** [comment]
Ok, I'm going to close this PR and recreate that after de uf-ext merge.
Thankls All

**Pull request closed without merging**
