### PR TITLE
[0.8.x] UF-284: Changes in CopyPopup and RenamePopup introduces a regresion in WB editors that has FileNameValidators configured for the different assets types

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by manstis** [comment]
@wmedvede Could you please take a look?

**Comment by manstis** [comment]
@paulovmr Thanks for closing the gap so quickly!

**Comment by paulovmr** [comment]
@manstis No problem :)

**Comment by wmedvede** [comment]
@csadilek 
+1  (0.8.x + 6.4.x branches tested)

**Comment by csadilek** [comment]
Thanks.

0.8.x: b811f825e06588a60a007f87b2c05f500585a7a0

**Pull request closed without merging**
