### PR TITLE
[UF-254] Layout Editor Improvements

### PR DESCRIPTION
**Pull request by ederign**
Squash of Pere's changes in layout editor
---------------------------------------------------------
* HasDragAndDropSettings: send other information information across the Drag & Drop event, not only the draggable type
* HasOnDropNotification: notify the draggable component that’s been droved
* HasOnRemoveNotification: notify the draggable component that’s going to be removed
* DynamicLayoutDraggableGroup: allow to add / remove dynamic component groups on the components palette. Also allow to add / remove child elements of the dynamic groups.

There is no enought test coverage in this PR because I'll continue to work on new features of layout editor and  there is a good chance of API changes.

In my next PR/commit I'll extract MVP from layout editor and improve his usability.

### CODE REVIEW

**Comment by csadilek** [comment]
Looks good to me. This is work in progress and it makes sense to send multiple PRs given the size of the planned changes. 

Two comments:
- We should no longer use UiBinder for new development and switch to Errai UI. (please update in a follow-up PR)
- This needs more test coverage (follow-up PR)

+1

**Comment by ederign** [comment]
@csadilek PR updated.

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
Thanks.

master: 7467a4b245213e3bcc08509fdebb499ae0f2d406

**Pull request closed without merging**
