### PR TITLE
Preserve Docks addition order when the corresponding icons are painted in the side bar

### PR DESCRIPTION
**Pull request by wmedvede**
It was already discussed to Eder to change the Docks container collection from Set to List, in order to preserve order when the docks are painted.

### CODE REVIEW

**Comment by wmedvede** [comment]
It will be GREAT if this PR can be merged and cherry-picked into 0.7.X in order to be included in kie-wb 6.3.Final release

**Comment by manstis** [comment]
SortedSet may be preferential since I doubt you want two instances of the same "Dock Widget" to be added to the "Dock" but will merge this PR anyway (I suspect we probably abuse use of List throughout the code base anyway...)

**Comment by wmedvede** [comment]
We discussed this already in the chat in favour of a List. On the other hand at are no defined criteria to make the Docks "Comparable", so I guess the list will work well. But whatever any other Collection you would like to use feel free to go ahead and change it.

**Comment by manstis** [comment]
*uberfire-extensions*
(master) http://github.com/uberfire/uberfire-extensions/commit/4cfaea389

(0.7.x) http://github.com/uberfire/uberfire-extensions/commit/767299307

**Comment by manstis** [comment]
Thanks @wmedvede

**Pull request closed without merging**
