### PR TITLE
UF-267: Perspective editor column is blocked after a component is added and closed

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by csadilek** [comment]
@paulovmr unfortunately, this is in conflict now. can you update it please? @ederign would you mind reviewing this one? thanks.

**Comment by csadilek** [comment]
@paulovmr nevermind, I will take care of the merge.

**Comment by paulovmr** [comment]
@csadilek I already did the merge, but I am also fixing a bug introduced with the Java 8 migration, so I can test my fix again. Currently, the Plugin Explorer doesn't load.

**Comment by csadilek** [comment]
@paulovmr ah ok. I will wait then. Thanks.

**Comment by paulovmr** [comment]
@csadilek I resolved the conflicts, and successfully tested it by commenting the problematic code (that doesn't impact here). 

I opened a [JIRA issue](https://issues.jboss.org/browse/UF-274) for the bug, and @ederign is taking a look.

**Comment by csadilek** [comment]
Thanks!

master: 0d612c191cdef04b67b59208d60acb33598f68f3

**Pull request closed without merging**
