### PR TITLE
Fix using Patternfly style instead of BS3

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@romartin please have a look on this. Workbench style got broken with BS3 overwriting PatternFly style. Here is a suggestion for fix but I'm not sure if it would break something in the Security Management side.

**Comment by romartin** [comment]
Hey @cristianonicolai! not sure at first glance.. so let me test the uf-extensions showcase for the security management with this commit, will give you feedback :)

**Comment by cristianonicolai** [comment]
thanks @romartin :)

**Comment by romartin** [comment]
Yeah @cristianonicolai , it looks good :) 
+1

**Comment by csadilek** [comment]
master: d8609e100a8d8752a9b7fa3a899702f2493053a3

**Pull request closed without merging**
