### PR TITLE
i18n BZs: 1284792 1284799 1284816 12848818

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Comment by manstis** [comment]
Way to go Eder! +1 to merge.

**Comment by ederign** [comment]
@manstis btw on 1284799 the screen title will remain the same
on 1284816 the place name will remain in english because is a uberfire concept.

is that right?

**Comment by manstis** [comment]
"Place Names" as in PlaceManager.goto("placeName") don't need to be i18n'ed as they are internal logical identifiers for physical screens and are not (should not) be exposed to Users. If we are exposing them to Users we should probably change to use a "regular" GWT PropertyBundle constant (ie like all other i18n).. Have I understood correctly?

**Comment by ederign** [comment]
I mean, On the edit screen popup there is a label called Place Name and a list with all the available screens/editors.

I don't think that translates this is a good idea because that is related with uberfire screen/editor identifier concept.

**Comment by ederign** [comment]
I've changed my mind! I'll i18n this! :)

**Comment by csadilek** [comment]
master: 5f9e274b7c6f016e75eaf480d7d18c8efa3f56af

**Pull request closed without merging**
