### PR TITLE
 Page Table extract - Build fix

### PR DESCRIPTION
**Pull request by Rikkola**
-Build fix

@ederign is this needed in any other branch?

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge (perhaps we can ask @maciejs?)

**Comment by Rikkola** [comment]
Checking if he is up. Also talking with @mbiarnes in IRC. Maybe he has permissions.

**Comment by Rikkola** [comment]
jenkins please retest

**Comment by psiroky** [comment]
There is a compilation error in Errai (mater branch), that's why the build is failing.

**Comment by Rikkola** [comment]
Ok. Good to know.

**Comment by psiroky** [comment]
Will merge this in few minutes.

**Comment by ederign** [comment]
@Rikkola Thanks! this is only on master.

**Pull request merged**
