### PR TITLE
FilterPagedTable remove content displayed when adding new filter

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by manstis** [comment]
I don't understand what this change brings, other than making the code more testable (with GwtMockito)?!?

**Comment by cristianonicolai** [comment]
The main point is to remove the string "Default", which is not translated and not really useful/necessary for displaying in the UI when creating a new filter.

**Comment by manstis** [comment]
Doh, no how much I looked at at last night I didn't see the "<Default>" text....

**Comment by manstis** [comment]
+1 to merge.

**Comment by csadilek** [comment]
master: 6479e2725c4cdc0aa728f0299d5e7c030b929304

**Pull request closed without merging**
