### PR TITLE
GUVNOR-2360 - Data Objects cannot be copied in the Authoring perspective

### PR DESCRIPTION
**Pull request by wmedvede**
- FileNameValidators expects the filename + extension.

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge.

**Comment by wmedvede** [comment]
@paulovmr 
Hello Paulo the following PR contains the fix the the small issue we chatted about with the CopyPopup. I saw that the same happens with the RenamePopup, so I've just fixed both. Tests remains the same, since the issue is that FileNameValidators expects the fileName + extensions.

If you can review it will be great.

**Comment by manstis** [comment]
@wmedvede Only one file changed in this PR (not ```RenamePopup```)

**Comment by manstis** [comment]
BTW I saw your chat on IRC.. so seeing the PR thought I'd +1 it..

**Comment by wmedvede** [comment]
@manstis ups, seems like I've forgot to add the RenamePopup

**Comment by wmedvede** [comment]
@manstis 

Both Copy and Rename popups added!
Ready to merge.

**Comment by csadilek** [comment]
@wmedvede @manstis -1, this is missing tests or better updates of the existing tests to verify that filename + extension is passed to the validator, not just any string.

**Comment by manstis** [comment]
@csadilek I was stood in the rain waiting for my son to come out of school and was thinking the exact same thing.. the JIRA was caused by a regression, so we should test for the same regression in the future.. should be a simple change.

**Comment by paulovmr** [comment]
@wmedvede Hi Walter, I agree with the change. Also, it will be necessary to change the following method, to remove the file extension in the "name" parameter, so the method works as before: https://github.com/uberfire/uberfire-extensions/blob/master/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/validation/PluginNameValidator.java#L78

**Comment by wmedvede** [comment]
@paulovmr  Hi Paulo, I'm not sure what you mean with "remove the extension" in the case of the plugins.
In the case of CopyPopup and RenamePopup the problem was that the popus removed the extension, but the file validators need the extension to perform the validation.
On the other hand If I create, copy, and rename a plugin it seems to work. So I don't know exactly how this affects the plugins.  ¿?

**Comment by paulovmr** [comment]
@wmedvede Yes, the validation still works with your change, but only because of the server-side, and only in some cases. In the client-side, this method that I mentioned makes the validation looking to the name of the registered plugins, and they are different from these plugins file names (and paths).

The following comparison would never be true if the "name" contains the file extension: https://github.com/uberfire/uberfire-extensions/blob/master/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/validation/PluginNameValidator.java#L92

**Comment by wmedvede** [comment]
@manstis @paulovmr 

Hello guys, according to what we chatted the following PR reverts the regression introduced by the plugins stuff. So I guess this PR can now be merged. Finally the following https://issues.jboss.org/browse/UF-284 was opened for investigation.

**Comment by paulovmr** [comment]
+1 to merge. I will work on this new ticket.

**Comment by csadilek** [comment]
0.8.x: e374ee36a69205f96eddfd03bed434495f2d311c

I (by mistake) pushed this to master as well. So, no need to send another PR :).

master: 4b7ae2187412d81a77658c67c3999d5ac17df0f8

**Pull request closed without merging**
