### PR TITLE
UF-292 : PlaceRequest parameters are cleared if the PlaceRequest is opened into a doc

### PR DESCRIPTION
**Pull request by Rikkola**
This fixes:
https://issues.jboss.org/browse/GUVNOR-2331
https://issues.jboss.org/browse/GUVNOR-2333

### CODE REVIEW

**Comment by ederign** [comment]
+1 @Rikkola thanks for fixing this!

**Comment by csadilek** [comment]
master: d39c8f14d2bd923496bd3ca02befd8dd50718ea1

**Comment by Rikkola** [comment]
Doc or Dock :)
What branch should I cherry-pick this to?

**Comment by csadilek** [comment]
@Rikkola I'd say only to 6.4.x. Thanks.

**Pull request closed without merging**
