### PR TITLE
Squashed changes from dgutierr pr: https://github.com/uberfire/uberfi…

### PR DESCRIPTION
**Pull request by ederign**
Squashed changes from dgutierr pr: https://github.com/uberfire/uberfire-extensions/pull/39
Some fixes on the PR by ederign
Small CSS improvements

### CODE REVIEW

**Comment by ederign** [comment]
@manstis after merge, should I cherry pick this somewhere?

**Comment by manstis** [comment]
My primary concern would be merging this before the BS3 upgrade is
complete. The PR affects the use of Accordion which is problematic with BS3
and merging would mean porcelli needs to revisit his work. @porcelli WDYT?

**Comment by ederign** [comment]
idk @manstis because without that PR, dashbuilder aren't on perspective editor for the release.

I've worked myself on upgrade of runtime plugins in BS3 and I can help with that in the future merge.

But it's your and @porcelli call.

**Comment by manstis** [comment]
Ok. I'll merge tomorrow (giving @porcelli until morning to stop me!). The
BS3 upgrade isn't for this release anyway. I don't think the PR need be
cherry-picked elsewhere (is there a new UF branch for 6.3.0.Final - I
didn't see one).

**Comment by manstis** [comment]
https://github.com/uberfire/uberfire-extensions/commit/219213182

**Pull request closed without merging**
