### PR TITLE
i18n BZs: 1284792 1284799 1284816 12848818

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Comment by manstis** [comment]
+1 to merge (don't forget 0.8.x too)

**Comment by ederign** [comment]
this is 0.8x :)

**Comment by ederign** [comment]
and thanks!

**Comment by manstis** [comment]
Hehe, ok my phone doesn't show branch names :-(

**Comment by csadilek** [comment]
0.8.x: cd8eb49f9fde36ae380b4a83e57a93c58379c82e

**Pull request closed without merging**
