### PR TITLE
GUVNOR-2452: improvements on YesNoCancellPopup in order to be more fl…

### PR DESCRIPTION
**Pull request by porcelli**
…exible in terms of size

### CODE REVIEW

**Comment by ederign** [comment]
+1. Optionally I would add tests for clearScrollHeight() method.

**Comment by porcelli** [comment]
Don't think tests would bring anything in this particular case, as to test it you'll have to mock the only possible side effect (the Element())

**Comment by ederign** [comment]
I would mock scroll panel, and make sure that after a YesNoCancelPopup.clearScrollHeight(), clear height for the panel was called. But again, optionally, not necessary. +1 anyway

**Comment by csadilek** [comment]
0.8.x: 9d95185d710600888710f0715e24a2d9cc9d595b

**Pull request closed without merging**
