### PR TITLE
Migrate to Lienzo 2.0.118-RC0

### PR DESCRIPTION
**Pull request by manstis**

### CODE REVIEW

**Comment by manstis** [comment]
IDK if you want to look at this.. it just updates a dependency and a bunch of package names etc.

(I don't like merging my own work, as I believe I should follow the same guidelines as everybody else).

**Comment by manstis** [comment]
Also see:

https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/75

https://github.com/droolsjbpm/guvnor/pull/133

https://github.com/droolsjbpm/drools-wb/pull/40

@porcelli, @dgutierr There will also (possibly) need to be changes to Dash Builder to use 2.0.118-RC0 (and a further change to guvnor-webapp, if the dashbuilder dependencies change).

**Comment by dgutierr** [comment]
Dashbuilder master has been also aligned with the suggested Lienzo release 2.0.118-RC0.
 
https://github.com/dashbuilder/dashbuilder/commit/09cbe0ac50924ac612bfe73d5242059ccd350537

**Comment by manstis** [comment]
@dgutierr Thanks.

Are you updating the dependent webapps too (or at least can you advise the new GAVs?)

```
[ERROR]   The project org.guvnor:guvnor-webapp:6.3.0-SNAPSHOT (/home/manstis/workspaces/git/manstis/forks/guvnor/guvnor-webapp/pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for org.dashbuilder:dashbuilder-lienzo-core:jar is missing. @ org.guvnor:guvnor-webapp:[unknown-version], /home/manstis/workspaces/git/manstis/forks/guvnor/guvnor-webapp/pom.xml, line 444, column 17
[ERROR]     'dependencies.dependency.version' for org.dashbuilder:dashbuilder-lienzo-charts:jar is missing. @ org.guvnor:guvnor-webapp:[unknown-version], /home/manstis/workspaces/git/manstis/forks/guvnor/guvnor-webapp/pom.xml, line 450, column 17
```

**Comment by dgutierr** [comment]
I realized the following deps needs to be removed:

org.dashbuilder:dashbuilder-lienzo-core
org.dashbuilder:dashbuilder-lienzo-charts

The poms affected are:

- guvnor/guvnor-webapp/pom.xml
- kie-wb-distributions/kie-wb/kie-wb-webapp/pom.xml
- kie-wb-distributions/kie-drools-wb/kie-drools-wb-webapp/pom.xml

I saw you already removed them in this PR https://github.com/droolsjbpm/guvnor/pull/133
You should do the same on kie-wb-distributions.

**Comment by manstis** [comment]
http://github.com/uberfire/uberfire-extensions/commit/78b00b174

**Pull request closed without merging**
